### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by FGRibreau** [QafooLabs/redis-testing#1]
It can't wait to get my hand on it @beberlei!

Your tool (even if it's a work in progress :)) will be **featured** shared in our next [RedisWeekly](http://redisweekly.com/)! Once published (in a matter of minutes) you will be able to see your [projet description here](http://redisweekly.com/archive/138.html) :)

**Comment by itamarhaber** [comment]
Totally agreeing - awesome.

**Comment by beberlei** [comment]
@FGRibreau thanks :-) I just needed this for a workshop with a customer, where we evaluated Redis. It will not be further developed.
